### PR TITLE
Don't normalize PeriodDuration on disk for derived types IntervalDayTime and IntervalMonthDayNano

### LINKED ISSUE #738: Test fail: interval add identity property
May be precision related

```
FAIL in (interval-add-identity-prop) (temporal_test.clj:633)
expected: {:result true}
  actual: {:shrunk {:total-nodes-visited 145, :depth 7, :pass? false, :result false, :result-data nil, :time-shrinking-ms 69, :smallest [#xt/interval-dt ["P0D" "PT-23H-59M-59.001S"]]}, :failed-after-ms 35, :num-tests 55, :seed 1680794245119, :fail [#xt/interval-mdn ["P36M42D" "PT-23H-59M-59.838977996S"]], :result false, :result-data nil, :failing-size 54, :pass? false, :test-var "interval-add-identity-prop"}
```

https://app.circleci.com/pipelines/github/wotbrew/core2/18/workflows/ea60e9e2-d9af-49df-a493-b11a149364bf/jobs/82

### PR DESCRIPTION
**Pull request by FiV0**
Fixes #738.

Also dissallow years and months in IntervalDayTime construction

### CODE REVIEW

File: api/src/main/java/xtdb/types/IntervalDayTime.java [hunk 1]
```diff
@@ -9,6 +9,8 @@ public final class IntervalDayTime {
     public final Duration duration;
 
     public IntervalDayTime(Period period, Duration duration) {
+        if ( period.getYears() != 0 || period.getMonths() != 0)
+            throw new java.lang.IllegalArgumentException("Period can not contain years or months!");
```
Comment (jarohen) [inline api/src/main/java/xtdb/types/IntervalDayTime.java:13]: you don't need to fully qualify `java.lang` in Java, it's auto-imported. also, prefer to use our `xtdb.IllegalArgumentException` (extends j.l.IAE) so that it gets correctly serialised over the wire

File: core/src/main/clojure/xtdb/vector.clj [hunk 2]
```diff
@@ -268,11 +268,10 @@
         (writeObject [_ v]
           (let [^PeriodDuration period-duration v
```
Comment (jarohen) [inline core/src/main/clojure/xtdb/vector.clj:269]: could you validate that PeriodDuration doesn't have a year/month part here, too? these won't hit your `IntervalDayTime` check.

**Review by jarohen — CHANGES_REQUESTED** [review]

File: core/src/main/clojure/xtdb/vector.clj (hunk 2 above)
Comment (FiV0) [reply core/src/main/clojure/xtdb/vector.clj:269]: I am just wondering how would we hit this?
